# Generated by Django 5.2.6 on 2025-09-29 09:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('jersey', 'Jersey'), ('sepatu', 'Sepatu Bola'), ('perlengkapan', 'Perlengkapan Latihan'), ('pakaian', 'Pakaian Kasual & Jaket'), ('aksesoris', 'Aksesoris'), ('memorabilia', 'Memorabilia'), ('lainnya', 'Lainnya')], default='lainnya', max_length=20)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('size', models.CharField(blank=True, choices=[('S', 'S - Small'), ('M', 'M - Medium'), ('L', 'L - Large'), ('XL', 'XL - Extra Large'), ('XXL', 'XXL - Double Extra Large'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('NA', 'N/A')], default='NA', max_length=5)),
                ('rating', models.FloatField(default=0.0)),
                ('product_views', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
